language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    $server

before_install:
  - 'openssl aes-256-cbc -K $encrypted_84a533ea9a4b_key -iv $encrypted_84a533ea9a4b_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d'

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
